# Site settings
title: US-GOSHIP
email: cchdo@ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
  This web site is supported by grant funds from the National 
  Science Foundation. Any opinions, findings, and conclusions 
  or recommendations expressed in this web site are those of 
  the PIs, James Swift and Lynne Talley, and do not necessarily 
  reflect the views of the supporting Federal agency.
baseurl: "/us-goship" # the subpath of your site, e.g. /blog/
url: "http://ushydro.ucsd.edu" # the base hostname & protocol for your site
twitter_username: ushydro
github_username:  

# Build settings
markdown: kramdown
